# Generated by Django 4.0.5 on 2022-06-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('restaurant_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('user_id', models.BigIntegerField()),
                ('author_name', models.CharField(max_length=255)),
                ('author_avatar', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('is_positive', models.SmallIntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
