# Generated by Django 4.0.5 on 2022-06-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0005_alter_comment_text_alter_comment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_positive',
            field=models.IntegerField(),
        ),
    ]
