# Generated by Django 4.0.5 on 2022-06-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0006_alter_comment_is_positive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=800),
        ),
    ]
