# Generated by Django 4.0.5 on 2022-06-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0007_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
