# Generated by Django 4.0.5 on 2022-06-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0008_alter_comment_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('is_positive', models.IntegerField()),
                ('text', models.CharField(max_length=255)),
            ],
        ),
    ]
